name: veptools
channels:
  - conda-forge
  - nvidia
  - bioconda
  - daler
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - black=24.8.0
  - bzip2=1.0.8
  - ca-certificates=2024.7.4
  - click=8.1.7
  - colorama=0.4.6
  - coverage=7.6.1
  - exceptiongroup=1.2.2
  - flake8=7.1.1
  - importlib-metadata=8.4.0
  - iniconfig=2.0.0
  - isort=5.13.2
  - ld_impl_linux-64=2.40
  - libblas=3.9.0
  - libcblas=3.9.0
  - libexpat=2.6.2
  - libffi=3.4.2
  - libgcc-ng=14.1.0
  - libgfortran-ng=14.1.0
  - libgfortran5=14.1.0
  - libgomp=14.1.0
  - liblapack=3.9.0
  - libnsl=2.0.1
  - libopenblas=0.3.27
  - libsqlite=3.46.0
  - libstdcxx-ng=14.1.0
  - libuuid=2.38.1
  - libxcrypt=4.4.36
  - libzlib=1.3.1
  - markdown-it-py=3.0.0
  - mccabe=0.7.0
  - mdurl=0.1.2
  - mypy=1.11.1
  - mypy_extensions=1.0.0
  - ncurses=6.5
  - numpy=2.1.0
  - openssl=3.3.1
  - packaging=24.1
  - pandas=2.2.2
  - pathspec=0.12.1
  - pep517=0.13.0
  - pip=24.2
  - platformdirs=4.2.2
  - pluggy=1.5.0
  - psutil=6.0.0
  - pycodestyle=2.12.1
  - pyflakes=3.2.0
  - pygments=2.18.0
  - pytest=8.3.2
  - python=3.12.5
  - python-dateutil=2.9.0
  - python-tzdata=2024.1
  - python_abi=3.12
  - pytz=2024.1
  - readline=8.2
  - rich=13.7.1
  - six=1.16.0
  - tk=8.6.13
  - tomli=2.0.1
  - types-setuptools=72.2.0.20240821
  - typing_extensions=4.12.2
  - tzdata=2024a
  - wheel=0.44.0
  - xz=5.2.6
  - zipp=3.20.0
  - pip:
      - pandas-stubs==2.2.2.240807
      - setuptools==73.0.1
      - types-openpyxl==3.1.5.20240822
      - types-pytz==2024.1.0.20240417
      - build==0.7.0
