name: dev
on:
  push:
  pull_request:
    types: [opened, reopened]

jobs:
  create-env:
    name: ${{ matrix.os }} 
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash -l {0}
        
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        
    steps:
      - name: checkout repository
        uses: actions/checkout@v2
        
      - name: create environment
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-activate-base: false
          activate-environment: veptools
          environment-file: environment.yaml
      
      - name: verify sha256 checksum
        run:
          make diff

      - name: lint via pylint
        run:
          make lint

      - name: test via pytest
        run:
          make test
