name: Lint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
    - uses: actions/checkout@v4
    - name: Installing dev environment
      run: |
        conda env create -f environment.yaml
    - name: Analysing the code with pylint
      run: |
        conda activate veptools
        make lint
