name: Lint

on: [push]

jobs:
  shell: bash -l {0}
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
    - uses: conda-incubator/setup-miniconda@v2
      with:
        activate-environment: anaconda-client-env
        environment-file: environment.yaml
        auto-activate-base: false
    - name: Analysing the code with pylint
      run: |
        conda activate veptools
        make lint
